//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace AssemblyCSharp
{
	public class DataReportObj
	{
		[JsonProperty("i")]
		public int Id { get; set; }
		[JsonProperty("h")]
		public double Happy { get; set; }
		[JsonProperty("x")]
		public double XCoord { get; set; }
		[JsonProperty("y")]
		public double YCoord { get; set; }
		[JsonProperty("d")]
		public string Description { get; set; }
		[JsonProperty("c")]
		public string Category { get; set; }
		[JsonProperty("t")]
		public string TimeStamp { get; set; }

		public DataReportObj ()
		{
		}

		public static DataReportObj CreateDataReportObj(int id, double happy, double xcoord, double ycoord, string description, string category, string timestamp) {
			DataReportObj dro = new DataReportObj ();

			dro.Id = id;
			dro.Happy = happy;
			dro.XCoord = xcoord;
			dro.YCoord = ycoord;
			dro.Description = description;
			dro.Category = category;
			dro.TimeStamp = timestamp;

			return dro;
		}

	}
}

