//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Newtonsoft.Json;

namespace AssemblyCSharp
{
	public class RootObject
	{

		[JsonProperty("success")]
		public string Success { get; set; }
		[JsonProperty("data")]
		public DataReportObj[] Data { get; set; }
		[JsonProperty("error")]
		public string Error { get; set; }

		public RootObject ()
		{
		}
	}
}

