//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine.UI;
using UnityEngine;

namespace AssemblyCSharp
{
	public class CameraController : MonoBehaviour
	{

		List<Camera> cameras = new List<Camera> ();
		public GameObject freeCam = null;

		public void Start() {
			//get all the cameras

			//cameras.AddRange (Camera.allCameras);

			cameras.Add (Camera.allCameras [0]);
			cameras.Add (Camera.allCameras [1]);
			cameras.Add (Camera.allCameras [2]);
			cameras.Add (Camera.allCameras [3]);
			cameras.Add (Camera.allCameras [4]);



		}

		public void Update() {

		}



		public CameraController ()
		{

		}

		public void CameraButton1Clicked() {
			cameraButtonClicked (1);
		}

		public void CameraButton2Clicked() {
			cameraButtonClicked (2);
		}

		public void CameraButton3Clicked() {
			cameraButtonClicked (3);
		}

		public void CameraButton4Clicked() {
			cameraButtonClicked (4);
		}

		public void CameraButton5Clicked() {
			cameraButtonClicked (5);
		}

		public void CameraButtonFreeClicked() {
			if (freeCam != null) {
				//expire other cams

				foreach(Camera curCam in cameras) {
					curCam.enabled = false;
					curCam.gameObject.SetActive(false);
				}

				freeCam.SetActive(true);
			}
		}

		private void cameraButtonClicked(int id) {

			//remove freecam
			freeCam.SetActive (false);

			foreach (Camera curCam in cameras) {
				if(curCam.name == string.Format("Camera{0}", id)) {
					curCam.enabled = true;
					curCam.gameObject.SetActive(true);
				}
				else {
					curCam.enabled = false;
					curCam.gameObject.SetActive(false);
				}
			}


		}
	}
}

