//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gov.cityofboston.hubhacks2.api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activation
    {
        public Activation()
        {
            this.Answers = new HashSet<Answer>();
            this.Demographics = new HashSet<Demographic>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastSeen { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Demographic> Demographics { get; set; }
    }
}
