//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gov.cityofboston.hubhacks2.api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public System.Guid Id { get; set; }
        public System.Guid ActivationId { get; set; }
        public System.Guid QuestionId { get; set; }
        public Nullable<decimal> AnswerLat { get; set; }
        public Nullable<decimal> AnswerLng { get; set; }
        public Nullable<bool> AnswerYesNo { get; set; }
        public Nullable<decimal> AnswerNumeric { get; set; }
    
        public virtual Activation Activation { get; set; }
        public virtual Question Question { get; set; }
    }
}
