//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gov.cityofboston.hubhacks2.api
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloudData
    {
        public int Id { get; set; }
        public decimal XCoord { get; set; }
        public decimal YCoord { get; set; }
        public bool IsRealtime { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public System.DateTime ItemTime { get; set; }
        public decimal HappyFactor { get; set; }
    }
}
