//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gov.cityofboston.hubhacks2.api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SurveyId { get; set; }
        public string QuestionText { get; set; }
        public int QuestionTypeId { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> QuestionOrder { get; set; }
        public string LabelLow { get; set; }
        public string LabelHigh { get; set; }
        public bool LabelHighGreen { get; set; }
        public bool YesAnswerBad { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
