//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gov.cityofboston.hubhacks2.api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taken
    {
        public System.Guid ActivationId { get; set; }
        public System.Guid SurveyId { get; set; }
        public bool Skipped { get; set; }
        public System.DateTime TakenDate { get; set; }
    
        public virtual Activation Activation { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
